meta:
  title: Ridge
  description: The best API documentation generator ever.
  siteUrl: https://ridge.redoc.ly
headerIcon: ./images/ridge.svg
enableToc: true
oasDefinitions:
  rks: ./api/rks.yaml
  rks-unstable: ./api/rks-unstable.yaml
  rcs: ./api/rcs.yaml
  rcs-unstable: ./api/rcs-unstable.yaml
  iam: ./api/iam.yaml
  iam-unstable: ./api/iam-unstable.yaml
  compute: ./api/compute.yaml
  compute-unstable: ./api/compute-unstable.yaml
  keyring: ./api/keyring.yaml
  keyring-unstable: ./api/keyring-unstable.yaml
stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto+Mono:300,400,600,700
  - https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700&display=swap
#ga:
  # you can use any options here from https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
  # note that GA doesn't work in DEV
#  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - label: Getting Started
    page: Getting Started/index.md
  - label: Docs
    page: docs/index.md
  - label: API Reference
    page: api/api-overview.md
  - search: true

footer:
  copyrightText: Copyright Â© Ridge 2021. All right reserved.
  columns:
    - group: Legal
      items:
        - label: Privacy Policy
          href: 'https://www.ridge.co/legal/privacy-policy'
        - label: Cookie Policy
          href: 'https://www.ridge.co/legal/cookies'
        - label: EULA
          href: 'https://www.ridge.co/legal/eula'
    - group: Support
      items:
        - label: Talk to Our Expert
          href: 'https://www.ridge.co/talk-to-expert'
    - group: Ridge.co
      items:
        - label: Homepage
          href: 'https://www.ridge.co'
        - label: Blog
          href: 'https://www.ridge.co/blog'
